# Generated by Django 3.2.1 on 2021-05-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_category',
            new_name='category',
        ),
    ]
