# Generated by Django 3.2.1 on 2021-05-14 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_bids', models.IntegerField()),
                ('listing_category', models.CharField(max_length=64)),
                ('listing_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
