# Generated by Django 3.2.1 on 2021-05-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210514_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_owner',
            new_name='listing_owner_id',
        ),
    ]
