# Generated by Django 3.2.1 on 2021-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='id',
            field=models.AutoField(auto_created=True, default='default', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
