# Generated by Django 3.2.1 on 2021-05-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210514_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_owner_id',
        ),
    ]
