# Generated by Django 3.2.1 on 2021-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_listing_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img_url',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
