# Generated by Django 3.2.1 on 2021-05-15 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_userslistings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslistings',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='userslistings',
            name='listing_id',
            field=models.ManyToManyField(related_name='listings', to='auctions.Listing'),
        ),
        migrations.RemoveField(
            model_name='userslistings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userslistings',
            name='user_id',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
