# Generated by Django 3.2.1 on 2021-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210515_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslistings',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='userslistings',
            name='listing_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userslistings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userslistings',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
