# Generated by Django 3.2.1 on 2021-05-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='highest_bidder_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='is_open',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
