# Generated by Django 3.2.1 on 2021-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210519_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
